### PR TITLE
Rebuild python3801

### PR DESCRIPTION
**Pull request by tacaswell**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

This extends and replaces #3

### CODE REVIEW

**Comment by tacaswell** [comment]
@conda-forge-admin, please rerender

**Comment by jjhelmus** [comment]
@melund I'm going to merge this without a review from the feedstock maintainers.  Let me know if you would like an additional maintainer, I'm happy to add myself.

**Comment by melund** [comment]
No problem. I actually just looking at this now. You are welcome to add yourself though. Thanks a lot @jjhelmus and @tacaswell

**Comment by tacaswell** [comment]
Thank you.  Sorry going out of band to get this merged, wanted to get it expedited and did not know you were on top of things @melund !

**Pull request merged**
